spring.application.name=video-game-store
server.port=${PORT:8080}

#####################
#   Secrets local   #
#####################
spring.config.import=optional:file:../secrets/secrets.properties

#####################
#    Secrets render  #
#####################

paypal.client.id=${paypalClientId}
paypal.client.secret=${paypalClientSecret}
jwt.seconds.valid=${jwtSecondsValid}
jwt.secret.key=${jwtSecretKey}
jwt.refresh.ttlSeconds=${jwtRefreshTtlSeconds}
spring.datasource.username=${springDatasourceUsername}

#####################
#       DB          #
#####################
spring.datasource.url=jdbc:h2:file:./data/vgstore;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.jdbc.core=DEBUG

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#####################
#       PayPal       #
#####################

#spring.config.import=optional:file:../secrets/secrets.properties

paypal.base-url=https://api-m.sandbox.paypal.com
paypal.return-url=${PORT:8080}/checkout/paypal/success
paypal.cancel-url=${PORT:8080}/checkout/paypal/cancel
paypal.brand-name=Video Game Store
paypal.currency=EUR